# ringqueue:SemCP.cpp
# 	g++ -o $@ $^ -std=c++11 -lpthread
# .PHONY:clean
# clean:
# 	rm -rf ringqueue


# threadpool:ThreadPool.cpp
# 	g++ -o $@ $^ -std=c++11 -lpthread
# .PHONY:clean
# clean:
# 	rm -rf threadpool

test:Test.cpp
	g++ -o $@ $^ -std=c++11 -lpthread
.PHONY:clean
clean:
	rm -rf test

