# threadCond:threadCond.cpp
# 	g++ -o $@ $^ -std=c++11 -lpthread
# .PHONY:clean
# clean:
# 	rm -rf threadCond
blockqueue:Main.cpp
	g++ -o $@ $^ -std=c++11 -lpthread
.PHONY:clean
clean:
	rm -rf blockqueue